version: '3.8'

services:
  comp01_module_a:
    image: nginx:latest
    container_name: comp01_module_a
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.comp01_module_a.rule: Host(`skill17.local/comp01/module_a`)
    volumes:
      - ./data/comp01/module_a:/usr/share/nginx/html
  comp01_module_b:
    image: nginx:latest
    container_name: comp01_module_b
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.comp01_module_b.rule: Host(`skill17.local/comp01/module_b`)
    volumes:
      - ./data/comp01/module_b:/usr/share/nginx/html
  comp01_module_c:
    image: nginx:latest
    container_name: comp01_module_c
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.comp01_module_c.rule: Host(`skill17.local/comp01/module_c`)
    volumes:
      - ./data/comp01/module_c:/usr/share/nginx/html
  comp02_module_a:
    image: nginx:latest
    container_name: comp02_module_a
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.comp02_module_a.rule: Host(`skill17.local/comp02/module_a`)
    volumes:
      - ./data/comp02/module_a:/usr/share/nginx/html
  comp02_module_b:
    image: nginx:latest
    container_name: comp02_module_b
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.comp02_module_b.rule: Host(`skill17.local/comp02/module_b`)
    volumes:
      - ./data/comp02/module_b:/usr/share/nginx/html
  comp02_module_c:
    image: nginx:latest
    container_name: comp02_module_c
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.comp02_module_c.rule: Host(`skill17.local/comp02/module_c`)
    volumes:
      - ./data/comp02/module_c:/usr/share/nginx/html

networks:
  gitea:
    external: true
