version: '3.8'

services:
  competitor1a:
    container_name: competitor-test-backend
    restart: always
    image: git.skill17.com/competitor-test/backend2:latest
    labels:
      traefik.enable: 'true'
      traefik.http.routers.competitor1a.rule: HostRegexp(`{_:e8f4sd\..*}`)
      traefik.http.routers.competitor1a.tls: true
      traefik.http.routers.competitor1a.entrypoints: websecure
      traefik.http.services.competitor1a.loadbalancer.server.port: 80
  competitor1b:
    container_name: competitor-test-frontend
    restart: always
    image: git.skill17.com/competitor-test/frontend:latest
    labels:
      traefik.enable: 'true'
      traefik.http.routers.competitor1b.rule: HostRegexp(`{_:dw5fgh\..*}`)
      traefik.http.routers.competitor1b.tls: true
      traefik.http.routers.competitor1b.entrypoints: websecure
      traefik.http.services.competitor1b.loadbalancer.server.port: 8080
