services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.21.7
    restart: always
    networks:
      - gitea
    labels:
      traefik.enable: 'true'
      traefik.http.routers.gitea.rule: Host(`git.${GITEA_HOSTNAME}`)
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.tls: true
      traefik.http.services.gitea.loadbalancer.server.port: 3000
    volumes:
      # - ./data/gitea:/data/gitea
      - ./config/gitea:/data/gitea/conf
      # - ./scripts:/scripts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__SERVER__ROOT_URL=https://git.${GITEA_HOSTNAME} 
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - gitea-db

  gitea-db:
    container_name: gitea-db
    image: mysql:8
    restart: always
    networks:
      - gitea
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./data/mysql-gitea:/var/lib/mysql

networks:
  gitea:
    external: true
